// Auto-generated by scripts/generate-dps-thresholds.ts
// Thresholds are per rarity and exact levelRequirement. Do not edit by hand.
export type DpsBands = { oneHandMax: number; twoHandMin: number };
export const DPS_THRESHOLDS: Record<string, Record<number, DpsBands>> = {
  "MYTHIC": {
    "40": {
      "oneHandMax": 670,
      "twoHandMin": 691
    }
  },
  "VERY_RARE": {
    "1": {
      "oneHandMax": 0,
      "twoHandMin": 0
    },
    "3": {
      "oneHandMax": 110,
      "twoHandMin": 126
    },
    "4": {
      "oneHandMax": 120,
      "twoHandMin": 138
    },
    "5": {
      "oneHandMax": 130,
      "twoHandMin": 150
    },
    "7": {
      "oneHandMax": 150,
      "twoHandMin": 173
    },
    "9": {
      "oneHandMax": 222,
      "twoHandMin": 235
    },
    "11": {
      "oneHandMax": 190,
      "twoHandMin": 218
    },
    "13": {
      "oneHandMax": 210,
      "twoHandMin": 241
    },
    "14": {
      "oneHandMax": 220,
      "twoHandMin": 270
    },
    "15": {
      "oneHandMax": 230,
      "twoHandMin": 282
    },
    "17": {
      "oneHandMax": 280,
      "twoHandMin": 300
    },
    "18": {
      "oneHandMax": 290,
      "twoHandMin": 356
    },
    "19": {
      "oneHandMax": 337,
      "twoHandMin": 342
    },
    "21": {
      "oneHandMax": 330,
      "twoHandMin": 379
    },
    "23": {
      "oneHandMax": 360,
      "twoHandMin": 441
    },
    "24": {
      "oneHandMax": 370,
      "twoHandMin": 454
    },
    "25": {
      "oneHandMax": 390,
      "twoHandMin": 413
    },
    "26": {
      "oneHandMax": 400,
      "twoHandMin": 490
    },
    "27": {
      "oneHandMax": 410,
      "twoHandMin": 437
    },
    "28": {
      "oneHandMax": 430,
      "twoHandMin": 513
    },
    "29": {
      "oneHandMax": 469,
      "twoHandMin": 481
    },
    "30": {
      "oneHandMax": 450,
      "twoHandMin": 523
    },
    "31": {
      "oneHandMax": 480,
      "twoHandMin": 547
    },
    "32": {
      "oneHandMax": 477,
      "twoHandMin": 549
    },
    "33": {
      "oneHandMax": 490,
      "twoHandMin": 601
    },
    "34": {
      "oneHandMax": 504,
      "twoHandMin": 622
    },
    "35": {
      "oneHandMax": 520,
      "twoHandMin": 637
    },
    "36": {
      "oneHandMax": 550,
      "twoHandMin": 674
    },
    "37": {
      "oneHandMax": 550,
      "twoHandMin": 638
    },
    "38": {
      "oneHandMax": 560,
      "twoHandMin": 646
    },
    "39": {
      "oneHandMax": 570,
      "twoHandMin": 654
    },
    "40": {
      "oneHandMax": 660,
      "twoHandMin": 699
    }
  },
  "RARE": {
    "1": {
      "oneHandMax": 0,
      "twoHandMin": 0
    },
    "2": {
      "oneHandMax": 90,
      "twoHandMin": 96
    },
    "4": {
      "oneHandMax": 120,
      "twoHandMin": 147
    },
    "5": {
      "oneHandMax": 120,
      "twoHandMin": 138
    },
    "6": {
      "oneHandMax": 129,
      "twoHandMin": 151
    },
    "7": {
      "oneHandMax": 140,
      "twoHandMin": 161
    },
    "8": {
      "oneHandMax": 150,
      "twoHandMin": 170
    },
    "9": {
      "oneHandMax": 170,
      "twoHandMin": 201
    },
    "10": {
      "oneHandMax": 160,
      "twoHandMin": 196
    },
    "11": {
      "oneHandMax": 180,
      "twoHandMin": 185
    },
    "12": {
      "oneHandMax": 200,
      "twoHandMin": 245
    },
    "13": {
      "oneHandMax": 210,
      "twoHandMin": 258
    },
    "14": {
      "oneHandMax": 200,
      "twoHandMin": 245
    },
    "15": {
      "oneHandMax": 220,
      "twoHandMin": 253
    },
    "16": {
      "oneHandMax": 230,
      "twoHandMin": 268
    },
    "17": {
      "oneHandMax": 250,
      "twoHandMin": 288
    },
    "18": {
      "oneHandMax": 239,
      "twoHandMin": 286
    },
    "19": {
      "oneHandMax": 280,
      "twoHandMin": 314
    },
    "20": {
      "oneHandMax": 290,
      "twoHandMin": 356
    },
    "21": {
      "oneHandMax": 300,
      "twoHandMin": 339
    },
    "22": {
      "oneHandMax": 340,
      "twoHandMin": 366
    },
    "23": {
      "oneHandMax": 330,
      "twoHandMin": 379
    },
    "24": {
      "oneHandMax": 360,
      "twoHandMin": 427
    },
    "25": {
      "oneHandMax": 350,
      "twoHandMin": 393
    },
    "26": {
      "oneHandMax": 370,
      "twoHandMin": 432
    },
    "27": {
      "oneHandMax": 370,
      "twoHandMin": 454
    },
    "28": {
      "oneHandMax": 380,
      "twoHandMin": 430
    },
    "29": {
      "oneHandMax": 460,
      "twoHandMin": 520
    },
    "30": {
      "oneHandMax": 420,
      "twoHandMin": 493
    },
    "31": {
      "oneHandMax": 450,
      "twoHandMin": 530
    },
    "32": {
      "oneHandMax": 430,
      "twoHandMin": 527
    },
    "33": {
      "oneHandMax": 470,
      "twoHandMin": 554
    },
    "34": {
      "oneHandMax": 504,
      "twoHandMin": 586
    },
    "35": {
      "oneHandMax": 470,
      "twoHandMin": 576
    },
    "36": {
      "oneHandMax": 490,
      "twoHandMin": 586
    },
    "37": {
      "oneHandMax": 490,
      "twoHandMin": 579
    },
    "38": {
      "oneHandMax": 470,
      "twoHandMin": 576
    },
    "39": {
      "oneHandMax": 510,
      "twoHandMin": 603
    },
    "40": {
      "oneHandMax": 540,
      "twoHandMin": 653
    }
  },
  "COMMON": {
    "1": {
      "oneHandMax": 70,
      "twoHandMin": 79
    },
    "2": {
      "oneHandMax": 90,
      "twoHandMin": 98
    },
    "4": {
      "oneHandMax": 100,
      "twoHandMin": 116
    },
    "5": {
      "oneHandMax": 110,
      "twoHandMin": 128
    },
    "6": {
      "oneHandMax": 120,
      "twoHandMin": 140
    },
    "7": {
      "oneHandMax": 130,
      "twoHandMin": 152
    },
    "8": {
      "oneHandMax": 140,
      "twoHandMin": 165
    },
    "9": {
      "oneHandMax": 150,
      "twoHandMin": 173
    },
    "11": {
      "oneHandMax": 170,
      "twoHandMin": 195
    },
    "13": {
      "oneHandMax": 190,
      "twoHandMin": 218
    }
  },
  "UNCOMMON": {
    "1": {
      "oneHandMax": 70,
      "twoHandMin": 79
    },
    "2": {
      "oneHandMax": 80,
      "twoHandMin": 84
    },
    "3": {
      "oneHandMax": 90,
      "twoHandMin": 111
    },
    "4": {
      "oneHandMax": 110,
      "twoHandMin": 113
    },
    "5": {
      "oneHandMax": 140,
      "twoHandMin": 157
    },
    "6": {
      "oneHandMax": 128,
      "twoHandMin": 151
    },
    "7": {
      "oneHandMax": 130,
      "twoHandMin": 160
    },
    "8": {
      "oneHandMax": 150,
      "twoHandMin": 177
    },
    "9": {
      "oneHandMax": 150,
      "twoHandMin": 173
    },
    "10": {
      "oneHandMax": 170,
      "twoHandMin": 195
    },
    "11": {
      "oneHandMax": 179,
      "twoHandMin": 198
    },
    "12": {
      "oneHandMax": 190,
      "twoHandMin": 233
    },
    "13": {
      "oneHandMax": 200,
      "twoHandMin": 231
    },
    "14": {
      "oneHandMax": 210,
      "twoHandMin": 243
    },
    "15": {
      "oneHandMax": 220,
      "twoHandMin": 270
    },
    "16": {
      "oneHandMax": 310,
      "twoHandMin": 315
    },
    "17": {
      "oneHandMax": 230,
      "twoHandMin": 265
    },
    "19": {
      "oneHandMax": 250,
      "twoHandMin": 299
    },
    "20": {
      "oneHandMax": 360,
      "twoHandMin": 441
    },
    "21": {
      "oneHandMax": 280,
      "twoHandMin": 343
    },
    "23": {
      "oneHandMax": 410,
      "twoHandMin": 503
    },
    "24": {
      "oneHandMax": 310,
      "twoHandMin": 366
    },
    "25": {
      "oneHandMax": 320,
      "twoHandMin": 392
    },
    "26": {
      "oneHandMax": 350,
      "twoHandMin": 415
    },
    "27": {
      "oneHandMax": 470,
      "twoHandMin": 576
    },
    "28": {
      "oneHandMax": 350,
      "twoHandMin": 429
    },
    "29": {
      "oneHandMax": 360,
      "twoHandMin": 427
    },
    "30": {
      "oneHandMax": 370,
      "twoHandMin": 454
    },
    "31": {
      "oneHandMax": 430,
      "twoHandMin": 491
    },
    "32": {
      "oneHandMax": 390,
      "twoHandMin": 478
    },
    "33": {
      "oneHandMax": 400,
      "twoHandMin": 490
    },
    "34": {
      "oneHandMax": 410,
      "twoHandMin": 488
    },
    "35": {
      "oneHandMax": 470,
      "twoHandMin": 540
    },
    "36": {
      "oneHandMax": 430,
      "twoHandMin": 527
    },
    "37": {
      "oneHandMax": 440,
      "twoHandMin": 539
    },
    "38": {
      "oneHandMax": 450,
      "twoHandMin": 518
    },
    "39": {
      "oneHandMax": 470,
      "twoHandMin": 554
    },
    "40": {
      "oneHandMax": 524,
      "twoHandMin": 610
    }
  }
} as const;
